---
- name: Install libcurl3-openssl-dev
  apt: pkg=libcurl3-openssl-dev state=installed install_recommends=no update-cache=yes cache_valid_time=3600

- name: restart php5-fpm process
  action: service name=php5-fpm state=restarted
  tags: common
