---

- name: Install python-pip for docker pip module
  action: apt pkg={{ item }} state=present install_recommends=no update-cache=yes
  tags: common
  with_items:
    - python-pip

- name: Install docker pip
  pip:
    name: docker

- name: copy the dockerfile
  template:
    src: "Dockerfile.j2"
    dest: /var/lib/Dockerfile
  when: dockerfile == "/var/lib/Dockerfile"

- name: Build the image
  docker_image:
    debug: true
    build_path: "{{ dockerfile }}"
    state: present
    name: "jekyll"
