---

- name: Install python-pip for docker pip module
  apt:
    pkg:
      - python-pip
    state: present
    install_recommends: false
    update-cache: true
    cache_valid_time: 3600
  tags: common

- name: upgrade pip with pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install docker pip
  pip:
    name: docker

- name: copy the dockerfile
  template:
    src: "Dockerfile.j2"
    dest: /var/lib/Dockerfile
  when: build_path == "/var/lib/"

- name: Build the image
  docker_image:
    debug: true
    build_path: "{{ build_path }}"
    state: present
    name: "jekyll"
#    force: true
