---

- name: Install python-pip for docker pip module
  apt:
    pkg:
      - python-pip
    state: present
    install_recommends: false
    update-cache: true
    cache_valid_time: 3600
  tags: common

- name: upgrade pip with pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install docker pip
  pip:
    name: docker

- name: make sure dockerfile holding directory exists
  file:
    path: "/tmp/ansible_{{ docker_image_name }}"
    state: directory

- name: copy the dockerfile
  copy:
    src: "{{ build_path }}/Dockerfile"
    dest: "/tmp/ansible_{{ docker_image_name }}/Dockerfile"

- name: Build the image
  docker_image:
    debug: true
    build_path: "/tmp/ansible_{{ docker_image_name }}/Dockerfile"
    state: present
    name: "{{ docker_image_name }}"
#    force: true
