---
- name: Start normal MySQL process
  service: name=mysql state=started
  tags: common

- name: Start normal MySQL process (docker)
  command: /etc/init.d/mysql restart
  when: is_docker is defined

- name: temporary tweak config to allow paswordless mysql instance
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf line="skip-grant-tables" insertafter="[mysqld]" state=present
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: temporary tweak config to allow paswordless mysql instance
  lineinfile: dest=/etc/mysql/my.cnf line="skip-grant-tables" insertafter="[mysqld]" state=present
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: temporary tweak config to not allow external connections to DB
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf line="skip-networking" insertafter="[mysqld]" state=present
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: temporary tweak config to not allow external connections to DB
  lineinfile: dest=/etc/mysql/my.cnf line="skip-networking" insertafter="[mysqld]" state=present
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: Restart normal MySQL process
  service: name=mysql state=restarted
  tags: common
  when: is_docker is not defined

- name: Restart normal MySQL process (docker)
  command: /etc/init.d/mysql restart
  when: is_docker is defined

- name: MySQL | add root user with grants for localhost < 16.04
  shell: mysql -u root -e 'use mysql;  REPLACE INTO user (Host,User,Password,Select_priv,Insert_priv,Grant_priv,Create_priv,Create_tmp_table_priv,Create_user_priv,Index_priv,Update_priv,Delete_priv,Create_tablespace_priv,Super_priv,Lock_tables_priv,Trigger_priv,Drop_priv,Reload_priv,Shutdown_priv,Process_priv,File_priv,References_priv,Alter_priv,Show_db_priv,Execute_priv,Create_view_priv,Show_view_priv,Create_routine_priv,Alter_routine_priv,Event_priv) VALUES("localhost","root",PASSWORD("{{ mysql_root_password }}"),"Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y");'
  tags: common
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: MySQL | add root user with grants for 127.0.0.1 < 16.04
  shell: mysql -u root -e 'use mysql;  REPLACE INTO user (Host,User,Password,Select_priv,Insert_priv,Grant_priv,Create_priv,Create_tmp_table_priv,Create_user_priv,Index_priv,Update_priv,Delete_priv,Create_tablespace_priv,Super_priv,Lock_tables_priv,Trigger_priv,Drop_priv,Reload_priv,Shutdown_priv,Process_priv,File_priv,References_priv,Alter_priv,Show_db_priv,Execute_priv,Create_view_priv,Show_view_priv,Create_routine_priv,Alter_routine_priv,Event_priv) VALUES("127.0.0.1","root",PASSWORD("{{ mysql_root_password }}"),"Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y");'
  tags: common
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: MySQL | add root user with grants for localhost >= 16.04
  shell: mysql -u root -e 'use mysql;  REPLACE INTO `user` VALUES ("localhost","root","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","","","","",0,0,0,0,"mysql_native_password",PASSWORD("{{ mysql_root_password }}"),"N",NOW(),NULL,"N");'
  tags: common
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: MySQL | add root user with grants for 127.0.0.1 >= 16.04
  shell: mysql -u root -e 'use mysql;  REPLACE INTO `user` VALUES ("127.0.0.1","root","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","Y","","","","",0,0,0,0,"mysql_native_password",PASSWORD("{{ mysql_root_password }}"),"N",NOW(),NULL,"N");'
  tags: common
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: temporary tweak config to DISABLE paswordless mysql instance
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf line="skip-grant-tables" state=absent
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: temporary tweak config to DISABLE paswordless mysql instance
  lineinfile: dest=/etc/mysql/my.cnf line="skip-grant-tables" state=absent
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: temporary tweak config to not ALLOW external connections to DB again
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf line="skip-networking" state=absent
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: temporary tweak config to not ALLOW external connections to DB again
  lineinfile: dest=/etc/mysql/my.cnf line="skip-networking" state=absent
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: Restart normal MySQL process
  service: name=mysql state=restarted
  tags: common

- name: Restart normal MySQL process (docker)
  command: /etc/init.d/mysql restart
  when: is_docker is defined
