---
- name: Copy files/folders needed on the remote
  copy: src="{{ item.source }}" dest="{{ item.destination }}" mode="{{ item.mode }}"
  with_items: "{{ file_sync_maps }}"
  when: item.mode is defined

- name: Copy files/folders needed on the remote
  copy: src="{{ item.source }}" dest="{{ item.destination }}"
  with_items: "{{ file_sync_maps }}"
  when: item.mode is not defined
