- name: Create User's db
  mysql_db:
    name:
      - "{{ mysql_user.db }}"
    state: present
  when: mysql_user.db != '*'

- name: Add User and their permissions to the db
  mysql_user:
      name: "{{ mysql_user.name }}"
      password: "{{ mysql_user.pass | default(lookup('password', mysql_pass_store_prefix + '/mysql_' + mysql_user.name +'_' + inventory_hostname +'_pass'), true) }}"
      priv: "{{ mysql_user.db }}.*:{{ mysql_user.grants | default(mysql_default_grants, true) }}"
      host: "{{ item }}"
      state: present
  loop: "{{ mysql_user.hosts }}"