---

- name: See if LXD is already initialize
  block:

  - shell: lxc storage list | grep default
    register: lxc_storage_result
    changed_when: false

  rescue:

    - debug:
        msg: "LXD not installed yet"

- name: Install & Init LXD if it wasn't before
  block:
    - name: Install SNAP
      apt:
        state: present
        name:
          - snapd

    - name: Remove apt packages
      apt:
        purge: true
        state: absent
        name:
          - lxd
          - lxd-client
          - liblxc1
          - lxcfs

    - name: Install lxd from snap
      snap:
        channel: "4.18/stable"
        name:
          - lxd

    - name: Install LXC back in
      apt:
        state: present
        update_cache: yes
        cache_valid_time: 3600
        name:
          - lxc
    # TODO: let's try to pre-seed it at some point as in https://lxd.readthedocs.io/en/latest/preseed/

    - name: Initialize LXD with specific device
      command: "lxd init --auto --storage-backend={{ lxd_storage_backend }} --storage-create-device={{ lxd_storage_device }}"
      when: lxd_storage_device is defined

    - name: Initialize LXD with specific device
      command: "lxd init --auto --storage-backend={{ lxd_storage_backend }}"
      when: lxd_storage_device is not defined

  when: lxc_storage_result.stdout is not defined or lxc_storage_result.stdout == ""