---

- name: LXD | Wrap version fetching
  block:
    - name: LXD | Get the current lxd version
      command: lxd --version
      register: lxd_version_output
      changed_when: false   # for idempodence

    - name: LXD | set concrete binary versions' facts
      set_fact:
        lxd_current_version: "{{ lxd_version_output.stdout | regex_search('[0-9]+\\.[0-9]+') }}"
  rescue:

    - name: LXD | set empty binary versions' facts
      set_fact:
        lxd_current_version: ""

- debug: LXD | Found version number
    var: lxd_current_version
  changed_when: true

- name: proceed with FRESH LXD installation
  include: install-fresh-lxd-ubuntu.yml
  when: lxd_current_version == ""

- name: proceed with existing LXD installation
  include: install-existing-lxd-ubuntu.yml
  when:
    - lxd_current_version != ""
    - lxd_current_version != lxd_version

- name: See if LXD is already initialized
  block:

  - shell: lxc storage list | grep default
    register: lxc_storage_result
    changed_when: false

  rescue:

    - debug:
        msg: "LXD not initialized yet"

- block:
    - name: Initialize LXD with specific device
      command: "lxd init --auto --storage-backend={{ lxd_storage_backend }} --storage-create-device={{ lxd_storage_device }}"
      when: lxd_storage_device is defined

    - name: Initialize LXD with specific device
      command: "lxd init --auto --storage-backend={{ lxd_storage_backend }}"
      when: lxd_storage_device is not defined

  when: lxc_storage_result.stdout is not defined or lxc_storage_result.stdout == ""

  # parenthesis only for clearance not for any Bool logic ^

- name: Install core dependencies needed to run molecule
  apt:
    name:
      - make
      - gcc
      - virtualenv
      - build-essential
      - jq
      - git-core
      - libyaml-dev
      - wget
      - unzip

- name: wrap python installation
  block:
    - name: install python-pip if it's there
      apt:
        name:
          - python-pip
          - python-dev

  rescue:

    - name: install python3-pip to the rescue
      apt:
        name:
          - python3-pip
          - python3-dev