---
- name: check if the host exists in the hosts file (delegated)
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^{{ host_config.name }}"
    insertafter: '^#Listen '
    line: "{{ host_config.name }} {{ host_config.dhcp }} {{ host_config.user }} {{ host_config.moreUsers }}"
  delegate_to: "{{ backuppc_server }}"
  when: backuppc_delegated

- name: check if the host exists in the hosts file
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^{{ host_config.name }}"
    insertafter: '^#Listen '
    line: "{{ host_config.name }} {{ host_config.dhcp }} {{ host_config.user }} {{ host_config.moreUsers }}"
  when: not backuppc_delegated