---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: mysql-test-ubuntu-1404
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-1404
verifier:
  name: testinfra
  lint:
    name: flake8
