---
##
# Ansible playbook for setting up an Apache web tier
#

##
# Apt package installation of required software.
#

- name: Fix SSL POODLE add new directive
  replace: dest=/etc/nginx/nginx.conf
    regexp='ssl_protocols (?!TLSv1 TLSv1.1 TLSv1.2);'
    replace='ssl_protocols TLSv1 TLSv1.1 TLSv1.2;'
  notify: Restart nginx
