---
- name: including debian vars
  include_vars: debian.yml
  when:  ansible_os_family == "Debian"

- name: including redhat vars
  include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- name: create includes folder
  file: path={{ monit_includes }} state=directory mode=0755

- name: config - copy pem file for ssl connections
  copy: src=../files/monit.pem dest=/etc/ssl/ mode=0700

- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: "{{monitrc_conf}}"
    owner: root
    group: root
    mode: 0700
  notify: restart monit

- name: config - Setup webinterface
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: root
    group: root
    mode: 0755
  notify: restart monit

- name: config - Setup mail alerts
  template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: root
    group: root
    mode: 0755
  notify: restart monit
  when: monit_mail_enabled
