---
- name: Install dependencies
  apt:
    pkg: ['libappindicator1', 'fonts-liberation', 'libasound2', 'libnspr4', 'libnss3', 'libxss1', 'xdg-utils', 'unzip']
    state: installed
    update-cache: yes
    install_recommends: no
    cache_valid_time: 3600

#- name: Copy google chrome's deb over to the machine
#  copy:
#    src: google-chrome-stable_current_amd64.deb
#    dest: /var/google-chrome-stable_current_amd64.deb

#- name: Copy chromedrivers' zip across
#  copy:
#    src: chromedriver_linux64_72.0.3626.7.zip
#    dest: /var/chromedriver_linux64_72.0.3626.7.zip

- name: Extract chromedrivers' binary
  unarchive:
    src: chromedriver_linux64_78.0.3904.70.zip
    dest: /usr/bin/
    mode: u=rwx,g=rx,o=rx
    creates: /usr/bin/chromedriver