---

- name: Install python-pip for docker pip module
  action: apt pkg={{ item }} state=present install_recommends=no update-cache=yes
  tags: common
  with_items:
    - python-pip

- name: Install docker pip
  pip:
    name: docker

- name: pull the jekyll image
  docker_image:
    name: jekyll/jekyll

- name: Create the jekyll container
  docker_container:
    name: jekyll
    image: jekyll/jekyll
    state: present
    volumes:
      - "{{ jekyll-docker-mount }}"
