---

- name: Install python-pip for docker pip module
  action: apt pkg={{ item }} state=present install_recommends=no update-cache=yes
  tags: common
  with_items:
    - python-pip

- name: Install docker pip
  pip:
    name: docker

- name: copy the dockerfile
  template:
    src: "Dockerfile.j2"
    dest: /var/lib/Dockerfile
  when: jekyll_dockerfile == "/var/lib/Dockerfile"

- name: Create the jekyll container
  docker_image:
    path: "{{ jekyll_dockerfile }}"
    state: present
