---

- name: Wrap >= 20 compat
  block:
    - name: legacy apt deb copy on >= 20
      copy:
        src: mysql-apt-config_0.8.12-1_all.deb
        dest: /var/lib/mysql-apt-config_0.8.12-1_all.deb
        mode: 0755

    - name: Install 5.7 repo on >= 20
      apt:
        deb: /var/lib/mysql-apt-config_0.8.12-1_all.deb
        only_upgrade: true
      notify: Innobackup Reload apt

    - name: Bodge missing apt pub key
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29

  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 20

- name: General | Install required packages < 20
  apt:
    name: ['mysql-server', 'python-mysqldb']
    state: present
    update-cache: yes
    cache_valid_time: 3600
#  notify: Mysql Installed
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 20
  register: "mysql_freshly_installed"

- name: General | Install required packages >= 20
  apt:
    name:
      - python3-mysqldb
      - mysql-client=5.7*
      - mysql-server=5.7*
    state: present
    force: yes
    update-cache: yes
#  notify: Mysql Installed
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 20
  register: "mysql_freshly_installed"

- debug:
    msg: "The value of mysql_freshly_installed is {{ mysql_freshly_installed }}"

- name: General | Install required auxiliary packages
  apt:
    name: ['mysql-client']
    state: present
    update-cache: yes
    cache_valid_time: 3600
    install_recommends: no

# temporary evade issue https://github.com/ansible/ansible/issues/14270#issuecomment-416880078
- include: handlers/mysql_initial_foldout.yml
  when: mysql_freshly_installed is defined and mysql_freshly_installed.changed == True

- name: MySQL | update default mysql mode for 16.04+
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^sql_mode'
    insertafter: '[mysqld]'
    line: 'sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16


- name: mysql remove bind directive from the base file
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    state: absent
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16
  notify: Restart mysql

- name: "Apply the mysql config file"
  template:
    src: "mysqld.cnf.j2"
    dest: "/etc/mysql/mysql.conf.d/99-ansible.cnf"
    mode: 0644
  notify: Restart mysql

- name: check if unattended upgrades config file exists
  stat:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
  register: unattended_config_check

- name: Skip mysql's unattended upgrading
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: '"mysql*";'
    insertafter: "^Unattended-Upgrade::Package-Blacklist {"
  when:
    - unattended_config_check.stat.exists == true
    - mysql_skip_unattended == true

- include: mysql-users.yml