---
# - name: Make sure mysql is up and running at this point
#  service: name=mysql state=started

# - name: Start normal MySQL process
#  service: name=mysql state=restarted
#  tags: common

- fail:
    msg: "[mysql_root_password] should be defined and not empty"
  when: mysql_root_password is not defined or mysql_root_password == ""

- name: MySQL | Config for easy access as root user
  action: template src=../templates/root-my-cnf.j2 dest=/root/.my.cnf
  tags: common
#  debugger: always

- name: MySQL | Config for easy access as ubuntu user on dev machines
  action: template src=../templates/root-my-cnf.j2 dest=/home/ubuntu/.my.cnf
  tags: common
  when: release_status is defined and release_status == "dev"

- name: MySQL | Config for easy access as ubuntu user on dev machines
  action: template src=../templates/root-my-cnf.j2 dest=/home/vagrant/.my.cnf
  tags: common
  when: release_status is defined and release_status == "dev"

# - name: add vagrant user for dev
#   mysql_user:
#     name: 'vagrant'
#     host: "%"
#     state: present
#     priv: "*.*:ALL"
#     password: "{{ mysql_root_password }}"
#   when: release_status is defined and release_status == "dev" and ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: add ubuntu user for dev
  mysql_user:
    name: 'ubuntu'
    host: "%"
    state: present
    priv: "*.*:ALL"
    login_host: 'localhost'
    password: "{{ mysql_root_password }}"
  when: release_status is defined and release_status == "dev" and ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16
