---
##
# Install libssh2
#
#

- name: Install required packages.
  apt:
    pkg:
      - libssh2-1-dev
      - libssh2-1
      - php-ssh2
    state: present
    install_recommends: false
    update-cache: true
    cache_valid_time: 3600
  tags: common

    # notify: Install ssh2 extensions for php 7.1
