---
##
# Install libssh2
#
#

- name: Install required packages.
  apt: pkg={{ item }} state=installed install_recommends=no update-cache=yes cache_valid_time=3600
  tags: common
  with_items:
    - libssh2-1-dev
    - libssh2-1
    - php-ssh2
    # notify: Install ssh2 extensions for php 7.1
