---
- name: Copy the zfs autosnapshot sources
  unarchive:
    src: zfs-auto-snapshot-upstream-1.2.4.tar.gz
    dest: /root/

- name: Run 'install' target as root
  make:
    chdir: /root/zfs-auto-snapshot-upstream-1.2.4
    target: install
  become: yes

- name: setup zfs snapshots's ENV
  cron:
    name: PATH
    env: true
    cron_file: zfs-auto-snapshot
    user: root
    job: "/usr/bin:/bin:/usr/sbin:/sbin"

# frequent snapshots are enabled by default
- name: setup frequent zfs snapshots
  cron:
    name: "frequent ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: "*/10"
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g -r--label=frequent --keep=24 {{ zfs_snapshot_filesystem }}"

- name: setup hourly zfs snapshots
  cron:
    name: "hourly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 0
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g -r --label=hourly --keep=24 {{ zfs_snapshot_filesystem }}"

- name: setup daily zfs snapshots
  cron:
    name: "daily ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 0
    hour: 23
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g -r --label=daily --keep=7 {{ zfs_snapshot_filesystem }}"

- name: setup weekly zfs snapshots
  cron:
    name: "weekly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 59
    hour: 23
    weekday: 0
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g -r --label=weekly --keep=2 {{ zfs_snapshot_filesystem }}"

- name: setup monthly zfs snapshots
  cron:
    name: "monthly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 2
    hour: 0
    day: 1
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g -r --label=monthly --keep=2 {{ zfs_snapshot_filesystem }}"

- name: disable auto-added hourly crontab
  cron:
    cron_file: /etc/cron.hourly/zfs-auto-snapshot
    state: absent

- name: disable auto-added daily crontab
  cron:
    cron_file: /etc/cron.daily/zfs-auto-snapshot
    state: absent

- name: disable auto-added weekly crontab
  cron:
    cron_file: /etc/cron.weekly/zfs-auto-snapshot
    state: absent

- name: disable auto-added monthly crontab
  cron:
    cron_file: /etc/cron.monthly/zfs-auto-snapshot
    state: absent

- name: Setup syncoid sync
  include: setup-syncoid.yml
  when: zfs_do_syncoid