---
- name: Copy the zfs autosnapshot sources
  unarchive:
    src: zfs-auto-snapshot-upstream-1.2.4.tar.gz
    dest: /root/

- name: Run 'install' target as root
  make:
    chdir: /root/zfs-auto-snapshot-upstream-1.2.4
    target: install
  become: yes

- name: setup zfs snapshots's ENV
  cron:
    name: PATH
    env: true
    cron_file: zfs-auto-snapshot
    user: root

- name: setup frequent zfs snapshots
  cron:
    name: "frequent ZFS snapshots"
    env: true
    cron_file: zfs-auto-snapshot
    user: root
    minute: "*/10"
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g --label=frequent --keep=24 //"

- name: setup hourly zfs snapshots
  cron:
    name: "hourly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 0
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g --label=hourly --keep=24 //"

- name: setup daily zfs snapshots
  cron:
    name: "daily ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 0
    hour: 23
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g --label=daily --keep=14 //"

- name: setup weekly zfs snapshots
  cron:
    name: "weekly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    minute: 59
    hour: 23
    weekday: 0
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g --label=weekly --keep=4 //"

- name: setup monthly zfs snapshots
  cron:
    name: "monthly ZFS snapshots"
    cron_file: zfs-auto-snapshot
    user: root
    env: true
    minute: 2
    hour: 0
    day: 1
    job: "/usr/local/sbin/zfs-auto-snapshot -q -g --label=monthly --keep=4 //"
