---
- name: Copy the syncoid script to the local bin
  file:
    src: files/syncoid
    dest: /usr/local/bin/syncoid
    mode: "u=rw,g=rx,o=rx"

- name: Materialize the syncoid runner script
  template:
    src: syncoid_sync.sh.j2
    dest: /usr/local/bin/syncoid_sync.sh
    mode: "u=rw,g=rx,o=rx"

- name: Setup cron to start the service on boot
  cron:
    name: "syncoid_sync"
    moniute: 50
    hour: "*/1"
    job: "/usr/local/bin/syncoid_sync.sh"
