---
- name: install required packages
  apt:
    name:
      - cpanminus
      - lzop
      - mbuffer
      - pv
    state: present

- name: Install syncoid deps
  cpanm:
    name: Capture::Tiny

- name: Copy the syncoid script to the local bin
  copy:
    src: syncoid
    dest: /usr/local/bin/syncoid
    mode: "u=rw,g=rx,o=rx"

- name: Materialize the syncoid runner script
  template:
    src: syncoid_sync.sh.j2
    dest: /usr/local/bin/syncoid_sync.sh
    mode: "u=rw,g=rx,o=rx"

- name: syncoid sync script to be ran on schedule
  cron:
    name: "syncoid_sync"
    minute: 50
    hour: "*/2"
    job: "/usr/local/bin/syncoid_sync.sh"
