---
##
# MySQL database setup, this does the equivalent of mysql_secure_installation.
#
# Distribution independent.
#


- name: Innobackupex deb copy
  copy: src=../files/percona-release_0.1-4.trusty_all.deb dest=/var/lib mode=0755
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: Innobackupex deb copy
  copy: src=../files/percona-release_0.1-4.xenial_all.deb dest=/var/lib mode=0755
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 16

- name: Innobackupex deb copy
  copy: src=../files/percona-release_latest.bionic_all.deb dest=/var/lib mode=0755
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 18

- name: Innobackupex deb copy focal
  copy: src=../files/percona-release_latest.focal_all.deb dest=/var/lib mode=0755
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 20


- name: Install innobackupex and related for db restores (trusty)
  apt:
    deb: /var/lib/percona-release_0.1-4.trusty_all.deb
    only_upgrade: true
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16
  notify: Innobackup Reload apt

- name: Install innobackupex and related for db restores (xenial)
  apt:
    deb: /var/lib/percona-release_0.1-4.xenial_all.deb
    only_upgrade: true
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 16
  notify: Innobackup Reload apt

- name: Install innobackupex and related for db restores (bionic)
  apt:
    deb: /var/lib/percona-release_latest.bionic_all.deb
    only_upgrade: true
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 18
  notify: Innobackup Reload apt
  ignore_errors: true

- name: Install innobackupex and related for db restores (focal)
  apt:
    deb: /var/lib/percona-release_latest.focal_all.deb
    only_upgrade: true
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int == 20
  notify: Innobackup Reload apt
  ignore_errors: true

- name: Install required packages.
  apt:
    pkg:
      - "{{ percona_version }}"
      - qpress
    state: present
    force: true
    install_recommends: false
    update-cache: true
