---
# ssh keys setup


# Using alternate directory locations:
- name: Add public keys for certain people to access the server
  authorized_key: user=root key="{{ lookup('file', item ) }}" state=present
  with_fileglob:
     - ssh_keys/maintainers/*
  tags: ssh-access-keys

# Using alternate directory locations:
- name: Remove old public keys
  authorized_key: user=root key="{{ lookup('file', item ) }}" state=absent
  with_fileglob:
       - ssh_keys/banned/*
  tags: ssh-access-keys