---
# ssh keys setup

# thanks https://jrs-s.net/2017/07/01/slow-ssh-logins/
- name: Disable useDNS (rip slow ssh login)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS no"
    line: "UseDNS no"
    state: present
  notify:
    - Restart ssh

- name: Keepalive sessions
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveInterval"
    line: "ClientAliveInterval 60"
    state: present
  notify:
    - Restart ssh

- name: Keepalive sessions
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveCountMax"
    line: "ClientAliveCountMax 60"
    state: present
  notify:
    - Restart ssh

# Using alternate directory locations:
- name: Add public keys for certain people to access the server
  authorized_key: user=root key="{{ lookup('file', item ) }}" state=present
  with_fileglob: "{{ ssh_keys_maintainers_allowed }}/*"
  tags: ssh-access-keys

# Using alternate directory locations:
- name: Remove old public keys
  authorized_key: user=root key="{{ lookup('file', item ) }}" state=absent
  with_fileglob: "{{ ssh_keys_maintainers_banned }}/*"
  tags: ssh-access-keys

