---
- name: Install libcurl3-openssl-dev
  apt: pkg=libcurl3-openssl-dev state=present install_recommends=no update-cache=yes cache_valid_time=3600

- name: restart php5-fpm process
  action: service name=php5-fpm state=restarted
  tags: common

- name: restart php7.2-fpm process
  action: service name=php7.2-fpm state=restarted
  tags: common

- name: restart php7.4-fpm process
  action: service name=php7.4-fpm state=restarted
  tags: common