---
- name: Install libcurl3-openssl-dev
  apt: pkg=libcurl3-openssl-dev state=present update-cache=yes install_recommends=no cache_valid_time=3600

- name: Restart Apache
  action: service name=apache2 state=restarted

- name: Restart PHP-FPM
  action: service name=php7.1-fpm state=restarted

- name: Restart PHP-FPM 7.2
  action: service name=php7.2-fpm state=restarted

- name: Restart PHP-FPM 7.3
  action: service name=php7.3-fpm state=restarted

- name: Restart PHP-FPM 7.4
  action: service name=php7.4-fpm state=restarted

- name: Restart PHP-FPM 8.2
  action: service name=php8.2-fpm state=restarted

- name: Setup hardening
  include: hardening.yml
  when: release_status is undefined or release_status != "dev"

- name: Apt update
  apt: update-cache=yes
