---
##

- name: Apache | Change the permissions of all the folders to 2775
  file: mode="02775" path="/var/www" state=directory
  changed_when: false

- name: Apache | Set umask mode
  replace: path=/etc/login.defs regexp="UMASK\t\t022" replace="UMASK    0002"
