---
##
# Install ID3
#
#

- name: copy sources
  copy: src=../files/php_pecl_id3-master.zip dest=/var/lib/id3.zip mode=0777

- name: unpack php5 version of ssh lib
  unarchive: copy=no src=/var/lib/id3.zip dest=/var/lib/ mode=0777 creates=/var/lib/php_pecl_id3-master

- name: Running ID3 .phpize
  command: phpize chdir=/var/lib/php_pecl_id3-master creates=/usr/lib/php/20220829/id3.so

- name: Running ID3 ./configure
  command: ./configure chdir=/var/lib/php_pecl_id3-master creates=/usr/lib/php/20220829/id3.so

- name: Running ID3 make
  command: make chdir=/var/lib/php_pecl_id3-master creates=/usr/lib/php/20220829/id3.so

- name: Running ID3 make install
  command: make install chdir=/var/lib/php_pecl_id3-master creates=/usr/lib/php/20220829/id3.so


- name: enable the ID3 extension in php cli
  lineinfile: dest=/etc/php/8.2/cli/php.ini line="extension=id3.so"

- name: enable the extension in php apache2
  lineinfile: dest=/etc/php/8.2/apache2/php.ini line="extension=id3.so"

- name: enable the extension in php fpm
  lineinfile: dest=/etc/php/8.2/fpm/php.ini line="extension=id3.so"
  when: apache_with_fpm is defined