---

- name: ffmpeg | Install required packages.
  action: apt pkg={{ item }} state=installed install_recommends=no update-cache=yes  cache_valid_time=3600
  tags: common
  with_items:
    - autoconf
    - automake
    - build-essential
    - libass-dev
    - libfreetype6-dev
    - libgpac-dev
    - libsdl1.2-dev
    - libtheora-dev
    - libtool
    - libva-dev
    - libvdpau-dev
    - libvorbis-dev
    - libx11-dev
    - libxext-dev
    - libxfixes-dev
    - pkg-config
    - texi2html
    - zlib1g-dev
    - unzip
    - libmp3lame-dev
    - libopus-dev
    - libmp3lame-dev
    - libfdk-aac-dev
    - libvpx-dev
    - libx264-dev
    - yasm
    - libass-dev
    - libtheora-dev
    - libvorbis-dev
    - mercurial
    - cmake

- name: copy yasm installation script
  copy: src=../files/compile_yasm.sh dest=/tmp mode=0777

- name: proper newline for yasm script
  shell: dos2unix /tmp/compile_yasm.sh

- name: execute yasm installation script
  command: /tmp/compile_yasm.sh creates=/root/bin/yasm


- name: copy x265 installation script
  copy: src=../files/compile_x265.sh dest=/tmp mode=0777

- name: proper newline for x265 script
  shell: dos2unix /tmp/compile_x265.sh

- name: execute x265 installation script
  command: /tmp/compile_x265.sh creates=/root/ffmpeg_build/bin/x265


- name: copy ffmpeg installation script
  copy: src=../files/compile_ffmpeg.sh dest=/tmp mode=0777

- name: proper newline for ffmpeg script
  shell: dos2unix /tmp/compile_ffmpeg.sh

- name: execute ffmpeg installation script
  command: /tmp/compile_ffmpeg.sh creates=/root/bin/ffmpeg


- name: Create /var/www/bin
  file:
    path: /var/www/bin
    state: directory
    mode: '0766'

- name: Copy ffmpeg bin files
  copy:
    remote_src: true
    src: /root/bin/
    dest: /var/www/bin/
    owner: www-data
    group: www-data
    mode: '0766'