---
#- name: Add nginx repo
#  apt_repository:
#    repo: 'ppa:nginx/stable'
#    state: present
#  notify: Nginx Update APT
#  delegate_to: localhost
#  delegate_facts: True

- name: General | Install required packages.
  command: "apt update"
  delegate_to: localhost

- name: General | Install required packages.
  command: "apt install nginx"
  delegate_to: localhost

- name: create self-signed SSL certs placeholder
  file: path="/etc/nginx/ssl" state="directory"
  delegate_to: localhost

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
  delegate_to: localhost

- name: Disable default vhost if not defined
  file: path="/etc/nginx/sites-enabled/default" state="absent"
  tags: common
  when: nginx_vhost is not defined
  delegate_to: localhost

- name: Copy nginx statics vhost
  template:
    src: proxy.conf.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
    mode: "u+x,g+x,o+x"
  delegate_to: localhost

- name: Enable nginx vhost
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}.conf"
    owner: www-data
    group: www-data
    state: link
  notify: Restart NGINX
  delegate_to: localhost

- name: Start nginx
  service: name=nginx state=started
  delegate_to: localhost
