---
##
# Ansible playbook for setting up an Apache web tier
#

##
# Apt package installation of required software.
#
- name: General | Install required packages.
  apt: pkg={{ item }} state=installed update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - libapache2-mod-php5
    - php5-mysql
    # this is a virtual package that will notify of changes in ansible when installed.
    # a way of finding it out: aptitude search '~v' | grep libcurl3-openssl-dev
    # - libcurl3-openssl-dev
    # so we want to make it a notification, and thus it would only run whenever some other "real" package changed

# this would indeally be branched based on php version. By since majority of our servers are php5.4+ now
# best to just silently fail in such cases and no enable the module. It's very rarely used.
# we will react if such thing happens
- name: Enable PHP5 IMAP module
  command: php5enmod imap creates=/etc/php5/cli/conf.d/20-imap.ini
  ignore_errors: true

- name: Enable PHP5 MCRYPT module
  command: php5enmod mcrypt creates=/etc/php5/cli/conf.d/20-mcrypt.ini
  ignore_errors: true

##
# PHP Setup.
#

# this would indeally be branched based on php version. By since majority of our servers are php5.4+ now
# best to just silently fail in such cases and no enable the module. It's very rarely used.
# we will react if such thing happens
# - name: Install pecl memcache
#   shell: printf "\n" | pecl install memcache
- name: Install pecl apc
  shell: printf "\n" | pecl install apc creates=/etc/php5/mods-available/apc.ini
  ignore_errors: true
  tags: php_config

- name: Install pecl pecl_http-1.7.6
  shell: printf "\n" | pecl install pecl_http-1.7.6 creates=/usr/share/php/pecl/http
  ignore_errors: true
  tags: php_config
  notify: Restart Apache

- name: PHP | Configuration file, php.ini
  action: template src=../templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  tags: php_config
  notify: Restart Apache


- name: PHP | (maybe) maintain compatibility with latest php versions
  file:
    src: '/etc/php5/mods-available'
    dest: '/etc/php5/conf.d'
    state: link
  ignore_errors: true
  tags: php_config
  notify: Restart Apache

- name: APC | Cache configuration file, apc.ini
  action: template src=../templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
  tags: php_config
  notify: Restart Apache


- name: APC | Cache configuration file, apc.ini
  action: template src=../templates/etc-php5-conf-d-common-ini.j2 dest=/etc/php5/conf.d/common.ini
  tags: php_config
  notify: Restart Apache
