---
##
# Ansible playbook for setting up an Apache web tier
#

##
# Apt package installation of required software.
#
- name: General | Install required packages.
  apt: pkg={{ item }} state=installed update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
#    - php7.2-mcrypt
    - php7.3-mysql

- name: Enable php-fpm 7.3 config for apache
  command: a2enconf php7.3-fpm
  when: apache_with_fpm

- name: php-fpm config
  lineinfile: dest=/etc/php/7.3/fpm/pool.d/www.conf line="listen = 127.0.0.1:7777" state=present
  notify:
    - Restart PHP-FPM 7.3
  when: apache_with_fpm

- name: php-fpm config
  lineinfile: dest=/etc/php/7.3/fpm/pool.d/www.conf line="listen = /run/php/php7.3-fpm.sock" state=absent
  notify:
    - Restart PHP-FPM 7.3
  when: apache_with_fpm

- name: Enable php7.3 memcached if needed
  file:
    src: /etc/php/7.3/mods-available/memcached.ini
    dest: /etc/php/7.3/fpm/conf.d/25-memcached.ini
    state: link
    force: true
  when: php_use_memcached and apache_with_fpm
  notify:
    - Restart PHP-FPM 7.3

- name: Flush Handlers.
  meta: flush_handlers


- name: Apache | Disable php7.1 module for FPM
  apache2_module: state=absent name={{item}}
  with_items:
    - php7.3
    - php7.2
    - php7.1
    - php7.0
  notify: Restart Apache
  ignore_errors: True
  when: apache_with_fpm

- debug:
    msg: "apache_with_fpm: {{ apache_with_fpm}}"

- name: Apache | Disable prefork module for php 7.3 + fpm
  apache2_module: state=absent name={{item}} ignore_configcheck=true
  with_items:
    - mpm_prefork
  notify: Restart Apache
  when: apache_with_fpm

- name: Apache | Enable event module for php 7.3 + fpm
  apache2_module: state=absent name={{item}} ignore_configcheck=true
  with_items:
    - mpm_event
  when: not apache_with_fpm

- name: Apache | Disable event module for php 7.3
  apache2_module: state=present name={{item}} ignore_configcheck=true
  with_items:
    - mpm_event
  when: apache_with_fpm

- name: Apache | Enable prefork module for php 7.3
  apache2_module: state=present name={{item}} ignore_configcheck=true
  with_items:
    - mpm_prefork
  notify: Restart Apache
  when: not apache_with_fpm

- name: General | Remove libapache mod php7.3 if using fpm.
  apt: pkg={{ item }} state=absent update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - libapache2-mod-php7.3
  when: apache_with_fpm

- name: General | Install libapache mod php7.3 if not using fpm.
  apt: pkg={{ item }} state=installed update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - libapache2-mod-php7.3
  when: not apache_with_fpm

- name: Apache | Enable php7.3 module
  apache2_module: state=present name={{item}}
  with_items:
    - php7.3
  notify: Restart Apache
  when: not apache_with_fpm
