---
##
# Ansible playbook for setting up an Apache web tier
#

##
# Apt package installation of required software.
#
- name: General | Install required packages.
  apt: pkg=php7.2-mysql state=present update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common

- name: Enable php-fpm 7.2 config for apache
  command: a2enconf php7.2-fpm
  when: apache_with_fpm

- name: php-fpm config
  lineinfile: dest=/etc/php/7.2/fpm/pool.d/www.conf line="listen = 127.0.0.1:7777" state=absent
  when: apache_with_fpm

- name: php-fpm config
  lineinfile: dest=/etc/php/7.2/fpm/pool.d/www.conf line="listen = /run/php/php7.2-fpm.sock" state=present
  notify:
    - Restart PHP-FPM 7.2
  when: apache_with_fpm

- name: Enable php7.2 memcached if needed
  file:
    src: /etc/php/7.2/mods-available/memcached.ini
    dest: /etc/php/7.2/fpm/conf.d/25-memcached.ini
    state: link
    force: true
  when: php_use_memcached and apache_with_fpm
  notify:
    - Restart PHP-FPM 7.2

- name: Flush Handlers.
  meta: flush_handlers


- name: Apache | Disable php7.1 module for FPM
  apache2_module: state=absent name={{item}}
  with_items:
    - php7.2
    - php7.1
    - php7.0
  notify: Restart Apache
  ignore_errors: True
  when: apache_with_fpm

- debug:
    msg: "apache_with_fpm: {{ apache_with_fpm}}"

- name: Apache | Disable prefork module for php 7.2 + fpm
  apache2_module: state=absent name=mpm_prefork ignore_configcheck=true
  notify: Restart Apache
  when: apache_with_fpm

- name: Apache | Enable event module for php 7.2 + fpm
  apache2_module: state=absent name=mpm_event ignore_configcheck=true
  when: not apache_with_fpm

- name: Apache | Disable event module for php 7.2
  apache2_module: state=present name=mpm_event ignore_configcheck=true
  when: apache_with_fpm

- name: Apache | Tweak mpm_event for php 7.2
  template: src=mpm_event.conf.j2 dest=/etc/apache2/mods-enabled/mpm_event.conf
  notify: Restart Apache
  when: apache_with_fpm

- name: Apache | Enable prefork module for php 7.2
  apache2_module: state=present name=mpm_prefork ignore_configcheck=true
  notify: Restart Apache
  when: not apache_with_fpm

- name: General | Remove libapache mod php7.2 if using fpm.
  apt: pkg=libapache2-mod-php7.2 state=absent update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  when: apache_with_fpm

- name: General | Install libapache mod php7.2 if not using fpm.
  apt: pkg=libapache2-mod-php7.2 state=present update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  when: not apache_with_fpm

- name: Apache | Enable php7.2 module
  apache2_module: state=present name=php7.2
  notify: Restart Apache
  when: not apache_with_fpm
