---
- name: enable the extension in php cli
  lineinfile: dest=/etc/php/7.3/cli/php.ini line="extension=mcrypt.so"

- name: enable the extension in php cli
  lineinfile: dest=/etc/php/7.3/fpm/php.ini line="extension=mcrypt.so"