---
- name: enable the extension in php cli
  lineinfile: dest=/etc/php/7.4/cli/php.ini line="extension=mcrypt.so"

- name: enable the extension in php fpm
  lineinfile: dest=/etc/php/7.4/fpm/php.ini line="extension=mcrypt.so"
  notify: Restart php7.4 FPM