---
- name: Restart mysql
  service: name=mysql state=restarted
  when: is_docker is not defined

- name: Restart mysql
  command: /etc/init.d/mysql restart
  when: is_docker is defined

- name: Mysql installed
  include: mysql_initial_foldout.yml
