---
- name: enable the extension in php cli
  lineinfile: dest=/etc/php/8.1/cli/php.ini line="extension=mcrypt.so"

- name: enable the extension in php fpm
  lineinfile: dest=/etc/php/8.1/fpm/php.ini line="extension=mcrypt.so"
  notify: Restart php8.1 FPM