---
- name: php-fpm config ini max execution time
  lineinfile: dest=/etc/php/7.3/fpm/php.ini regex="(?!max_execution_time = {{ fpm_max_execution_time }})max_execution_time.*" state=absent

- name: php-fpm config ini max execution time
  lineinfile: dest=/etc/php/7.3/fpm/php.ini line="max_execution_time = {{ fpm_max_execution_time }}" state=present insertbefore="max_input_time"
  notify:
    - Restart PHP-FPM

- name: php-fpm config ini max memory consumption
  lineinfile: dest=/etc/php/7.3/fpm/php.ini regex="(?!memory_limit = {{ fpm_max_memory }})memory_limit.*" state=absent

- name: php-fpm config ini max memory consumption
  lineinfile: dest=/etc/php/7.3/fpm/php.ini line="memory_limit = {{ fpm_max_memory }}" state=present insertbefore="max_input_time"
  notify:
    - Restart PHP-FPM

- name: materialize fpm pool config
  template: src=www.conf.j2 dest=/etc/php/7.3/fpm/pool.d/www.conf
  notify:
    - Restart PHP-FPM