---
- name: Convert the share name to systemd-understandable entity
  shell: "/bin/systemd-escape {{ item.target | regex_replace('^\\/|\\/$', '') }}"
  register: systemd_escaped
  changed_when: false
  check_mode: false  # execute in check mode too

- name: Copy service file template, remove trailing and leading slashes, replace other to the form systemd wants them in
  template: src=nfs-client.mount.j2 dest="/lib/systemd/system/{{ systemd_escaped.stdout }}.mount"
  register: nfs_service_result

- systemd:
    daemon_reload: yes
  when: nfs_service_result.changed

- name: Enable the nfs-client service
  service: name="{{ systemd_escaped.stdout }}.mount" enabled=true

- name: Start the nfs-client service
  service: name="{{ systemd_escaped.stdout }}.mount" state=started