---
- name: Copy service file template, remove trailing and leading slashes, replace other to the form systemd wants them in
  template: src=nfs-client.mount.j2 dest="/lib/systemd/system/{{ (item.target) | regex_replace('^\\/|\\/$', '')  | replace('/','-') }}.mount"

- name: Enable the nfs-client service
  service: name="{{ (item.target) | regex_replace('^\\/|\\/$', '')  | replace('/','-') }}.mount" enabled=true

- name: Start the nfs-client service
  service: name="{{ (item.target) | regex_replace('^\\/|\\/$', '')  | replace('/','-') }}.mount" state=started