---
- name: Copy service file template
  template: src=nfs-client.mount.j2 dest="/lib/systemd/system/{{ (item.target)[1:] | replace('/','_') }}.mount"

- name: Enable the nfs-client service
  service: name="{{ (item.target)[1:] | replace('/','_') }}.mount" enabled=true

- name: Start the nfs-client service
  service: name="{{ (item.target)[1:] | replace('/','_') }}.mount" state=started