---

  - name: Ensure NFS common is installed.
    apt: name=nfs-common state=installed update_cache=yes cache_valid_time=3600

  - name: Create mountable dir
    file: path="{{ item.target }}" state=directory mode=777 owner=root group=root
    with_items: "{{ nfs_mounts }}"

  - name: set mountpoints
    mount: name="{{ item.target }}" src="{{ item.source }}" fstype=nfs dump=0 passno=2 state=mounted
    with_items: "{{ nfs_mounts }}"