monit_cycle: 60
monit_log_destination: /var/log/monit.log
monit_state_file: /var/lib/monit/state
monit_id_file: /var/lib/monit/id
monit_monitor_loadavg: true
monit_services: []
monit_service_delete_unlisted: true
monit_monit_swap: true
monit_monit_cpu: true
monit_monit_mem: true

monit_mail_enabled: false
monit_mailserver_host: localhost
monit_mailserver_port: 25

monit_webinterface_enabled: true
monit_webinterface_bind: 127.0.0.1
monit_webinterface_port: 2812

monit_apache_rules:
 - "if totalcpu > 80% for 3 cycles then alert"
 - "if totalmem > 400.0 MB for 5 cycles then alert"
 - "if children > 250 then alert"
 - "if loadavg(5min) > 20 for 8 cycles then alert"

monit_memcached_rules:
 - "if failed host 127.0.0.1 port 11211 protocol MEMCACHE then restart"
 - "if cpu > 80% for 3 cycles then alert"
