#!/bin/sh

echo
echo " ********************************************************"
echo " * This server is configured using Ansible               "
echo " * You put your hands on line                            "
echo " * if you start fiddling with it manually                "
echo " * The train is coming *chooo* *chooo*                   "
echo " ********************************************************"
echo
