---

- name: Copy over mysql key
  copy:
    # keyserver: keys.gnupg.net
    src: mysql.key
    dest: /tmp/mysql.key

- name: Add official MySQL package authentication key
  apt_key:
    # keyserver: keys.gnupg.net
    id: 5072E1F5
    file: /tmp/mysql.key
    state: present

- name: Add MySQL repository
  apt_repository:
    repo: deb http://repo.mysql.com/apt/debian/ stretch mysql-8.0
    filename: mysql80
    state: present

- name: Set MySQL root password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/root-pass
    value: "{{ mysql_root_password }}"
    vtype: password

- name: Confirm MySQL root password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/re-root-pass
    value: "{{ mysql_root_password }}"
    vtype: password

- name: Enable Legacy Authentication Method
  debconf:
    name: mysql-community-server
    question: mysql-server/default-auth-override
    value: Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)
    vtype: select

- name: Install/Update MySQL 8.0 Community Server
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - mysql-server
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: "mysql_freshly_installed"


- name: General | Install required packages.
  apt:
    name: ['python-mysqldb']
    state: present
    update-cache: yes
    cache_valid_time: 3600
#  notify: Mysql Installed
  when: ansible_distribution == 'Ubuntu'
  register: "mysql_freshly_installed"

- debug:
    msg: "The value of mysql_freshly_installed is {{ mysql_freshly_installed }}"

- name: General | Install required auxiliary packages
  apt:
    name: ['mysql-client']
    state: present
    update-cache: yes
    cache_valid_time: 3600
    install_recommends: no

# temporary evade issue https://github.com/ansible/ansible/issues/14270#issuecomment-416880078
- include: handlers/mysql_initial_foldout.yml
  when: mysql_freshly_installed is defined and mysql_freshly_installed.changed == True

- name: MySQL | update default mysql mode for mysql 8
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^sql_mode'
    insertafter: '[mysqld]'
    line: 'sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: mysql remove localhost-only bind
  replace: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="[\t ]*bind-address[\t ]*=[\t ]*127\.0\.0\.1" replace="bind-address = 0.0.0.0"
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16
  notify: Restart mysql

- include: mysql-users.yml