---
- name: enable the extension in php cli
  lineinfile: dest=/etc/php/8.2/cli/php.ini line="extension=mcrypt.so"

- name: enable the extension in php fpm
  lineinfile: dest=/etc/php/8.2/fpm/php.ini line="extension=mcrypt.so"
  notify: Restart php8.2 FPM