- name: Copy vhost
  template: src="{{ template }}" dest="/etc/nginx/sites-available/{{ server_name }}.conf" mode="u+x,g+x,o+x"
  notify: Reload Nginx

- name: etc/hosts entries to point to self
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ item.server_name }} {{ item.server_aliases|join(' ') }}"
    state: present

- name: Enable vhost
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    owner: www-data
    group: www-data
    state: link
  notify: Reload Nginx