---
##
# Ansible playbook for setting up an Apache web tier
#

##
# Apt package installation of required software.
#
- name: Install required packages.
  apt:
    pkg:
      - ufw
      - fail2ban
      - logwatch
    state: present
    update-cache: true
    install_recommends: false
    cache_valid_time: 3600
  tags: common

- name: UFW allow ssh access
  ufw: rule=allow port=ssh proto=tcp

- name: UFW allow custom rules
  ufw: rule=allow port="{{ item.port }}" src="{{ item.from }}" proto="{{ item.proto | default('any')}}"
  with_items: "{{ ufw_allow }}"

- name: UFW allow custom rules
  ufw: rule=deny port="{{ item.port }}" src="{{ item.from }}" proto="{{ item.proto | default('any')}}"
  with_items: "{{ ufw_deny }}"

- name: Enable ufw
  ufw: state=enabled

- name: Start ufw service
  service:
    name: ufw
    state: started

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify:
    - Restart ssh

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present install_recommends=no
  when: with_unattended is true

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=absent install_recommends=no
  when: with_unattended is false

- name: Adjust APT update intervals
  template: src=../templates/apt-periodic.j2 dest=/etc/apt/apt.conf.d/10periodic
  when: with_unattended is true

- name: Make logwatch mail {{ logwatch_email }} daily
  action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high" state=present create=yes
