---
##
# Install ID3
#
#

- name: copy sources
  copy: src=../files/php_pecl_id3-master.zip dest=/tmp/id3.zip mode=0777
  tags: libssh2

- name: unpack php5 version of ssh lib
  unarchive: src=/tmp/id3.zip dest=/tmp/ mode=0777 creates=/tmp/php_pecl_id3-master

- name: Running .phpize
  command: phpize chdir=/tmp/php_pecl_id3-master creates=/usr/lib/php/20151012/id3.so

- name: Running ./configure
  command: ./configure chdir=/tmp/php_pecl_id3-master creates=/usr/lib/php/20151012/id3.so

- name: Running make
  command: make chdir=/tmp/php_pecl_id3-master creates=/usr/lib/php/20151012/id3.so

- name: Running make install
  command: make install chdir=/tmp/php_pecl_id3-master creates=/usr/lib/php/20151012/id3.so


- name: enable the extension in php cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini line="extension=id3.so"

- name: enable the extension in php cli
  lineinfile: dest=/etc/php/7.0/apache2/php.ini line="extension=id3.so"


