---
##
# Ansible playbook for augmenting Apache web tier with drupal
#
##
# Apt package installation of required software.
#
- name: General | Install required packages.
  action: apt pkg={{ item }} state=installed install_recommends=no
  tags: common
  with_items:
    - php5-xdebug
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: General | Install required packages.
  action: apt pkg={{ item }} state=installed install_recommends=no
  tags: common
  with_items:
    - php-xdebug
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16