---
##
# Ansible playbook for augmenting Apache web tier with drupal
#
##
# Apt package installation of required software.
#
- name: General | Install required packages.
  action: apt pkg={{ item }} state=present install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - php5-xdebug
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int < 16

- name: General | Install required packages.
  action: apt pkg={{ item }} state=present install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - "php{{ php_version }}-xdebug"
  when: ansible_distribution == 'Ubuntu' and  ansible_lsb.major_release|int >= 16

- name: Configure the xdebug for PHPSTORM
  blockinfile:
    path: "/etc/php/{{ php_version }}/mods-available/xdebug.ini"
    block: "{{ xdebug_config }}"
    insertafter: EOF
    marker: "; {mark} ANSIBLE PHPSTORM MODS"