---

- name: Install GPG package
  apt:
    name:
      - gpg
    state: present
    update-cache: yes
    cache_valid_time: 3600

- name: Add syncthing's signing key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add syncthing apt repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
  register: "syncthing_repo_added"

- name: Update repositories after syncthing repo added
  apt:
    update_cache: yes
  when: syncthing_repo_added is defined and syncthing_repo_added.changed == True

- name: Install syncthing's package
  apt:
    name:
      - syncthing
    state: present
    update-cache: yes
    cache_valid_time: 3600

- name: Copy service file template
  copy: src=syncthing.service dest=/lib/systemd/system/syncthing.service

- name: Enable the syncthing service
  service: name=syncthing.service enabled=true

- name: Start the custom redis service
  service: name=syncthing.service state=started