---
- name: General | Install required packages.
  apt: pkg={{ item }} state=installed update-cache=yes install_recommends=no cache_valid_time=3600
  tags: common
  with_items:
    - memcached
    - libmemcached-tools
